In [ ]:
x=5
m=8
y="9"
z="2"
print(type(x))
print(type(y))
print(x+m)
print(y+z)


<class 'int'>
<class 'str'>
13
92


In [ ]:
a=int(z)
#typecasting
print(a+m)

10


In [ ]:
#List
l1=[53,56,8.8,70,8.0,'list',[3,59,'Hello World!']]
l2=l1[6][2][0:5]
print(l2)
length=len(l1)
print(length)

Hello
7


In [ ]:
#Tuple
t1=(6,7,'Vir')
print(t1)

(6, 7, 'Vir')


In [ ]:
#illustrate a list
nums=[]
nums.append(21)
nums.append("Viraj")
nums.append(40.6)

print(nums)

[21, 'Viraj', 40.6]


In [ ]:
#Dictionary
d1={"Name":"Viraj","Age":"19"}
print(d1)
print(type(d1))
print(d1.keys())


{'Name': 'Viraj', 'Age': '19'}
<class 'dict'>
dict_keys(['Name', 'Age'])


In [ ]:
#Dict with Input
num1= float(input("Enter the number:"))
if(num1>=80):
  print("1st class pass")
elif(num1>=60):
  print("Passed")
else:
  print("Failed")


Enter the number:89.78
1st class pass


In [ ]:
#Numpy
import numpy as np

#Array with Rank1
arr=np.array([[7,8,9]])
#Array with Rank2
arr=np.array([[7,8,9],["hello",True,56.7]])

#Printing array
print(arr)

#peinting array dimension
print("No. of dimensions",arr.ndim)

#printing shape of array
print("Shape of array",arr.shape)

#peinting size
print("Size of array",arr.size)

#Printing type of elements in array
print("Array stores element of type:",arr.dtype)
print("Array is of type:",type(arr))



[['7' '8' '9']
 ['hello' 'True' '56.7']]
No. of dimensions 2
Shape of array (2, 3)
Size of array 6
Array stores element of type: <U32
Array is of type: <class 'numpy.ndarray'>


In [ ]:
import numpy as np

#creating array
arr=np.array([2,4,6,8,10])

#creating copy of array
c=arr.copy()

#both arr and c have different id
print("id of arr",id(arr))
print("id of c",id(c))

#changing original array
#this will not affect copy
arr[0]=67

#printing array and copy
print("original array:",arr)

print("copy:",c)

def sum(array):
  sum=0
  for i in array:
    sum+=i
  return sum

testArray=[1,2,3,4]

print('The sum of your number is '+str(sum(testArray)))


id of arr 133910540083888
id of c 133910540090320
original array: [67  4  6  8 10]
copy: [ 2  4  6  8 10]
The sum of your number is 10


In [ ]:
import numpy as np
a=np.arange(10,1,-2)
newarr=a[np.array([3,1,2])]  #fancy indexing in numpy
print("\n Element at these indices are:\n",newarr)



 Element at these indices are:
 [4 8 6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
#The copy is not affected by the changes made to the original array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#The copy is affected by the changes made to the original array
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#The result includes the start index, but excludes the end index

import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
#Check if array owns its data
#copies owns the data, and views does not own the data

import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
#Create an array with 5 dimensions using ndim
#using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

newarr=arr.reshape(2,3,2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[9,10]])
print(np.add(x,y))
print()
print(np.subtract(x,y))
print()
print(np.multiply(x,y))
print()
print(np.divide(x,y))

[[ 8 10]
 [13 15]]

[[-6 -6]
 [-5 -5]]

[[ 7 16]
 [36 50]]

[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
import pandas as pd

mydataset={
    'Owner Name':"Viraj Oza",
    'Cars':["BM0W","Audi"]
}

myvar=pd.DataFrame(mydataset)
print(myvar)

  Owner Name  Cars
0  Viraj Oza  BM0W
1  Viraj Oza  Audi


In [ ]:
#Version string of Pandas
import pandas as pd
print(pd.__version__)

2.0.3


In [ ]:
#a pandas series is like a column in a table
import pandas as pd
a=[1,7,2]
myvar=pd.Series(a)
print(myvar)
print(myvar[1])


0    1
1    7
2    2
dtype: int64
7


In [ ]:
import pandas as pd
a=["India","America","UK"]
myvar=pd.Series(a,index=["a","b","c"])
print(myvar)
print(myvar['a'])

a      India
b    America
c         UK
dtype: object
India


In [ ]:
import pandas as pd
data={
    "calories":[420,340,780],
    "duration":[50,40,80]
}

#Load data into DataFrame object:
df=pd.DataFrame(data)
print(df)

#Pandas  use the loc attribute to return one or more specified rows
print(df.loc[0])
print(df.loc[1])

   calories  duration
0       420        50
1       340        40
2       780        80
calories    420
duration     50
Name: 0, dtype: int64
calories    340
duration     40
Name: 1, dtype: int64


In [ ]:
import pandas as pd
df= pd.read_csv('sample_data/mnist_test.csv')
print(df)

      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665

In [ ]:
import pandas as pd
df= pd.read_csv('Data.csv')
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd
print(pd.options.display.max_rows)
# The number of rows returned is defined in Pandas option settings.

60


In [ ]:
import pandas as pd
pd.options.display.max_rows=9999
df=pd.read_csv('Data.csv')
print(df)
print(pd.options.display.max_rows)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
9999


In [ ]:
#Load a Python dictionary into a DataFrame     JSON=Python Dictionary

import pandas as pd

data={
    "Duration":{
        "0":60,
        "1":60,
        "2":60,
        "3":60,
        "4":60,
        "5":60,
        "6":60,
        "7":60
    },
     "Pulses":{
        "0":110,
        "1":117,
        "2":103,
        "3":109,
        "4":117,
        "5":102
    },
     "Maxpulse":{
        "0":130,
        "1":145,
        "2":135,
        "3":175,
        "4":148,
        "5":127,
    },
     "Calories":{
        "0":409,
        "1":479,
        "2":340,
        "3":282,
        "4":406,
        "5":300
    }
}

df=pd.DataFrame(data)
print(df)


   Duration  Pulses  Maxpulse  Calories
0        60   110.0     130.0     409.0
1        60   117.0     145.0     479.0
2        60   103.0     135.0     340.0
3        60   109.0     175.0     282.0
4        60   117.0     148.0     406.0
5        60   102.0     127.0     300.0
6        60     NaN       NaN       NaN
7        60     NaN       NaN       NaN


In [ ]:

import pandas as pd

#creating first dataframe
df1=pd.DataFrame({"fruit":["apple","banana","mango"],
                  "market_price":[21,34,50]})
display("The first dataframe")
display(df1)

#creating second dataframe

df2=pd.DataFrame({"fruit":["banana","apple","strawberry"],
                 "wholesaler_price":[56,78,90]})
display("The second dataframe")
display(df2)

# Joining two DataFrames
display("The merged DataFrame:")
pd.merge(df1,df2,on="fruit",how="inner")
# how; {'left','right','outer','inner'}

'The first dataframe'

fruit  market_price
0   apple            21
1  banana            34
2   mango            50

'The second dataframe'

fruit  wholesaler_price
0      banana                56
1       apple                78
2  strawberry                90

'The merged DataFrame:'

fruit  market_price  wholesaler_price
0   apple            21                78
1  banana            34                56

from matplotlib import pyplot as plt
_df_0['market_price'].plot(kind='hist', bins=20, title='market_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['wholesaler_price'].plot(kind='hist', bins=20, title='wholesaler_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('fruit').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='market_price', y='wholesaler_price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['market_price']
  ys = series['wholesaler_price']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('market_price', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('fruit')):
  _plot_series(series, series_name, i)
  fig.legend(title='fruit', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('market_price')
_ = plt.ylabel('wholesaler_price')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['market_price']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'market_price'}, axis=1)
              .sort_values('market_price', ascending=True))
  xs = counted['market_price']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('market_price', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('fruit')):
  _plot_series(series, series_name, i)
  fig.legend(title='fruit', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('market_price')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_6['market_price'].plot(kind='line', figsize=(8, 4), title='market_price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['wholesaler_price'].plot(kind='line', figsize=(8, 4), title='wholesaler_price')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_8['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_8, x='market_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_9['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_9, x='wholesaler_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:

#groupby() function is used to split the data into groups based on some criteria.
#Pandas objects can be split on any of their axes

import pandas as pd

#Creating the Dataframe
df=pd.read_csv("Data.csv")

print(df.head()) # head returns top 5 rows by default

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [ ]:
#Indentation
j=1
while(j<=7):
  print(j)
  j+=1

  if(j==5):
      break


1
2
3
4
